<?php
 /**
  * Base file for HTML processing
  *
  * @author Gouverneur Thomas <tgouverneur@be.tiauto.com>
  * @copyright Copyright (c) 2007-2008, Gouverneur Thomas - TI Automotive
  * @version 1.0
  * @package html
  * @subpackage html
  * @category html
  * @filesource
  */
?>
<?php
 require_once("./lib/autoload.lib.php");
 require_once("./lib/html.lib.php");

 /* sanitize _GET and _POST */
 sanitizeArray($_GET);
 sanitizeArray($_POST);

 /* connect to the database: */
 if (!Mysql::getInstance()->connect())
 { echo "Cannot connect to mysql database<br/>\n"; die(); }

 $main = Main::getInstance();
 $main->fetchMonoId();
 $main->fetchMonoDetails();

 if (isset($_GET["action"])) $action = $_GET["action"];
 if (isset($_POST["action"])) $action = $_POST["action"];
 if (!isset($action)) $action = 1;

 if (isset($_GET["mid"])) $mid = $_GET["mid"];
 if (isset($_POST["mid"])) $mid = $_POST["mid"];
 if (isset($mid)) { 
   $mono = new Monowall($mid);
   $mono->fetchFromId();
   $mono->fetchSyslog();
   $syslog = $mono->syslog;
 }    
?>

<p class="pgtitle">Syslog: Edit</p>

<?php if ($action == 1) { ?>
<script language="JavaScript">
<!--
function enable_change(enable_over) {
	if (document.iform.enable.checked || enable_over) {
		document.iform.remoteserver.disabled = 0;
		document.iform.filter.disabled = 0;
		document.iform.dhcp.disabled = 0;
		document.iform.portalauth.disabled = 0;
		document.iform.vpn.disabled = 0;
		document.iform.system.disabled = 0;
	} else {
		document.iform.remoteserver.disabled = 1;
		document.iform.filter.disabled = 1;
		document.iform.dhcp.disabled = 1;
		document.iform.portalauth.disabled = 1;
		document.iform.vpn.disabled = 1;
		document.iform.system.disabled = 1;
	}
}
// -->
</script>
<form action="sysmod.php" method="post" name="iform" id="iform">
<table width="100%" border="0" cellpadding="6" cellspacing="0">
                      <tr> 
                        <td width="22%" valign="top" class="vtable">&nbsp;</td>
                        <td width="78%" class="vtable"> <input name="reverse" type="checkbox" id="reverse" value="yes" <?php if ($syslog->reverse) echo "checked"; ?>>
                          <strong>Show log entries in reverse order (newest entries 
                          on top)</strong></td>
                      </tr>
                      <tr> 
                        <td width="22%" valign="top" class="vtable">&nbsp;</td>
                        <td width="78%" class="vtable">Number of log entries to 
                          show: 
                          <input name="nentries" id="nentries" type="text" class="formfld" size="4" value="<?=htmlspecialchars($syslog->nentries);?>"></td>
                      </tr>
                      <tr> 
                        <td valign="top" class="vtable">&nbsp;</td>
                        <td class="vtable"> <input name="logdefaultblock" type="checkbox" id="logdefaultblock" value="yes" <?php if (!$syslog->nologdefaultblock) echo "checked"; ?>>
                          <strong>Log packets blocked by the default rule</strong><br>
                          Hint: packets that are blocked by the 
                          implicit default block rule will not be logged anymore 
                          if you uncheck this option. Per-rule logging options are not affected.</td>
                      </tr>
                      <tr> 
                        <td valign="top" class="vtable">&nbsp;</td>
                        <td class="vtable"> <input name="rawfilter" type="checkbox" id="rawfilter" value="yes" <?php if ($syslog->rawfilter) echo "checked"; ?>>
                          <strong>Show raw filter logs</strong><br>
                          Hint: If this is checked, filter logs are shown as generated by the packet filter, without any formatting. This will reveal more detailed information. </td>
                      </tr>
                      <tr> 
                        <td valign="top" class="vtable">&nbsp;</td>
                        <td class="vtable"> <input name="resolve" type="checkbox" id="resolve" value="yes" <?php if ($syslog->resolve) echo "checked"; ?>>
                          <strong>Resolve IP addresses to hostnames</strong><br>
                          Hint: If this is checked, IP addresses in firewall logs are resolved to real hostnames where possible.<br>
                          Warning: This can cause a huge delay in loading the firewall log page!</td>
                      </tr>
                      <tr> 
                        <td width="22%" valign="top" class="vtable">&nbsp;</td>
                        <td width="78%" class="vtable"> <input name="enable" type="checkbox" id="enable" value="yes" <?php if ($syslog->enable) echo "checked"; ?> onClick="enable_change(false)">
                          <strong>Enable syslog'ing to remote syslog server</strong></td>
                      </tr>
                      <tr> 
                        <td width="22%" valign="top" class="vncell">Remote syslog 
                          server</td>
                        <td width="78%" class="vtable"> <input name="remoteserver" id="remoteserver" type="text" class="formfld" size="20" value="<?=htmlspecialchars($syslog->remoteserver);?>"> 
                          <br>
                          IP address of remote syslog server<br> <br>
						  <input name="system" id="system" type="checkbox" value="yes" onclick="enable_change(false)" <?php if ($syslog->system) echo "checked"; ?>>
                          system events <br>
						  <input name="filter" id="filter" type="checkbox" value="yes" <?php if ($syslog->filter) echo "checked"; ?>>
                          firewall events<br>
						  <input name="dhcp" id="dhcp" type="checkbox" value="yes" <?php if ($syslog->dhcp) echo "checked"; ?>>
                          DHCP service events<br>
						  <input name="portalauth" id="portalauth" type="checkbox" value="yes" <?php if ($syslog->portalauth) echo "checked"; ?>>
                          Captive portal<br> 
						  <input name="vpn" id="vpn" type="checkbox" value="yes" <?php if ($syslog->vpn) echo "checked"; ?>>
                          PPTP VPN events</td>
                      </tr>
                      <tr> 
                        <td width="22%" valign="top">&nbsp;</td>
                        <td width="78%"> <input name="Submit" type="submit" class="formbtn" value="Save" onclick="enable_change(true)"> 
                        </td>
                      </tr>
                      <tr> 
                        <td width="22%" valign="top">&nbsp;</td>
                        <td width="78%"><strong><span class="red">Note:</span></strong><br>
                          syslog sends UDP datagrams to port 514 on the specified 
                          remote syslog server. Be sure to set syslogd on the 
                          remote server to accept syslog messages from m0n0wall. 
                        </td>
                      </tr>
                    </table>
   <input name="mid" type="hidden" value="<?=$mono->id;?>">
<?php if (isset($mono) && $mono) { ?>
<input name="action" type="hidden" value="3">
<?php } else { ?>
<input name="action" type="hidden" value="2">
<?php } ?>
</form>
<script language="JavaScript">
<!--
enable_change(false);
//-->
</script>

<?php

} else if ($action == 2) /* add */ {

/* can't add syslog parameters as there are only one per m0n0 device */
echo "blop.<br/>";

} else if ($action == 3) /* mod */ {

 if (!isset($syslog)) {
   echo "Error while loading syslog settings.<br/>";
   die();
 }
 $mod = 0;

 if (checkPost("reverse") && $_POST["reverse"] == yes && !$syslog->reverse) {
  $syslog->reverse = 1;
  $mod = 1;
 } else {
  if ($syslog->reverse == 1 && !checkPost("reverse")) {
   $syslog->reverse = 0;
   $mod = 1;
  }
 }

 if (checkPost("nentries") && $_POST["nentries"] != $syslog->nentries) {
  $syslog->nentries = $_POST["nentries"];
  $mod = 1;
 }

  if (checkPost("rawfilter") && $_POST["rawfilter"] == "yes" && !$syslog->rawfilter) {
  $syslog->rawfilter = 1;
  $mod = 1;
 } else {
  if ($syslog->rawfilter == 1 && !checkPost("rawfilter")) {
   $syslog->rawfilter = 0;
   $mod = 1;
  }
 }

 if (checkPost("resolve") && $_POST["resolve"] == "yes" && !$syslog->resolve) {
  $syslog->resolve= 1;
  $mod = 1;
 } else {
  if ($syslog->resolve == 1 && !checkPost("resolve")) {
   $syslog->resolve = 0;
   $mod = 1;
  }
 }

 if (checkPost("enable") && $_POST["enable"] == "yes" && !$syslog->enable) {
  $syslog->enable = 1;
  $mod = 1;
 } else {
  if ($syslog->enable == 1 && !checkPost("enable")) {
   $syslog->enable = 0;
   $mod = 1;
  }
 }

 if (checkPost("remoteserver") && $_POST["remoteserver"] != $syslog->remoteserver) {
  $syslog->remoteserver = $_POST["remoteserver"];
  $mod = 1;
 }

 if (checkPost("system") && $_POST["system"] == "yes" && !$syslog->system) {
  $syslog->system = 1;
  $mod = 1;
 } else {
  if ($syslog->system == 1 && !checkPost("system")) {
   $syslog->system = 0;
   $mod = 1;
  }
 }

 if (checkPost("filter") && $_POST["filter"] == "yes" && !$syslog->filter) {
  $syslog->filter = 1;
  $mod = 1;
 } else {
  if ($syslog->filter == 1 && !checkPost("filter")) {
   $syslog->filter = 0;
   $mod = 1;
  }
 }

 if (checkPost("dhcp") && $_POST["dhcp"] == "yes" && !$syslog->dhcp) {
  $syslog->dhcp = 1;
  $mod = 1;
 } else {
  if ($syslog->dhcp == 1 && !checkPost("dhcp")) {
   $syslog->dhcp = 0;
   $mod = 1;
  }
 }

 if (checkPost("portalauth") && $_POST["portalauth"] == "yes" && !$syslog->portalauth) {
  $syslog->portalauth= 1;
  $mod = 1;
 } else {
  if ($syslog->portalauth== 1 && !checkPost("portalauth")) {
   $syslog->portalauth= 0;
   $mod = 1;
  }
 }

 if (checkPost("vpn") && $_POST["vpn"] == "yes" && !$syslog->vpn) {
  $syslog->vpn= 1;
  $mod = 1;
 } else {
  if ($syslog->vpn == 1 && !checkPost("vpn")) {
   $syslog->vpn = 0;
   $mod = 1;
  }
 }

 if ($mod) {

  $syslog->update();
  $mono->updateChanged();
  echo "Syslog settings updated...<br/>";
 }
 else echo "Nothing to update..<br/>";

}

 /* disconnect database */
 Mysql::getInstance()->disconnect();
?>
